# Generated by Django 5.2.1 on 2025-07-08 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro_api', '0002_motivasi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motivasi',
            old_name='sumber',
            new_name='pembuat',
        ),
    ]
