# Generated by Django 5.2.1 on 2025-07-24 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro_api', '0005_timeentry_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='user',
        ),
    ]
